# Form implementation generated from reading ui file 'interfaz1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 781)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_superior = QtWidgets.QFrame(parent=self.frame)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 42))
        self.frame_superior.setStyleSheet("QFrame{\n"
"background-color: rgb(54, 54, 54);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(54, 54, 54);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    background-color: rgb(103, 103, 103);\n"
"    border-radius: 20px;\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bt_menu = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_menu.setMinimumSize(QtCore.QSize(200, 0))
        self.bt_menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("iconos/2931145_bullet_list_menu_note_playlist_icon.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_menu.setIcon(icon)
        self.bt_menu.setIconSize(QtCore.QSize(38, 38))
        self.bt_menu.setObjectName("bt_menu")
        self.horizontalLayout_2.addWidget(self.bt_menu)
        spacerItem = QtWidgets.QSpacerItem(485, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.bt_min = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_min.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_min.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("iconos/2931142_minimize_minus_remove_line_icon.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_min.setIcon(icon1)
        self.bt_min.setIconSize(QtCore.QSize(25, 25))
        self.bt_min.setObjectName("bt_min")
        self.horizontalLayout_2.addWidget(self.bt_min)
        self.bt_ventana = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_ventana.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_ventana.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("iconos/2931153_clone_copy_duplicate_multiply_clipboard_icon.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_ventana.setIcon(icon2)
        self.bt_ventana.setIconSize(QtCore.QSize(25, 25))
        self.bt_ventana.setObjectName("bt_ventana")
        self.horizontalLayout_2.addWidget(self.bt_ventana)
        self.bt_cerrar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_cerrar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_cerrar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("iconos/2931151_close_delete_exit_remove_x_icon.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_cerrar.setIcon(icon3)
        self.bt_cerrar.setIconSize(QtCore.QSize(25, 25))
        self.bt_cerrar.setObjectName("bt_cerrar")
        self.horizontalLayout_2.addWidget(self.bt_cerrar)
        self.verticalLayout.addWidget(self.frame_superior)
        self.frame_contenido = QtWidgets.QFrame(parent=self.frame)
        self.frame_contenido.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_contenido.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_contenido.setObjectName("frame_contenido")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_contenido)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_control = QtWidgets.QFrame(parent=self.frame_contenido)
        self.frame_control.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_control.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_control.setStyleSheet("QFrame{\n"
"    background-color: rgb(103, 103, 103)\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(54, 54, 54);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 77 13pt \"Century Gothic\";\n"
"    border-radius: 20px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(150, 150, 150);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    \n"
"    font: 77 13pt \"Century Gothic\";\n"
"}")
        self.frame_control.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_control.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_control.setObjectName("frame_control")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_control)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_control)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("iconos/2931174_clipboard_copy_paste_analysis_report_icon.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_control)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_2.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("iconos/2931185_door_enter_exit_leave_out_icon.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon5)
        self.pushButton_2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_control)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_3.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("iconos/2931168_bin_delete_remove_trash_garbage_icon.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon6)
        self.pushButton_3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_control)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_4.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("iconos/2931178_change_edit_pencil_creative_design_icon.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_4.setIcon(icon7)
        self.pushButton_4.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame_control)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_5.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("iconos/2931190_fit_search_zoom_glass_view_icon.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_5.setIcon(icon8)
        self.pushButton_5.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.horizontalLayout_3.addWidget(self.frame_control)
        self.frame_paginas = QtWidgets.QFrame(parent=self.frame_contenido)
        self.frame_paginas.setStyleSheet("QFrame{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(103, 103, 103);\n"
"}\n"
"\n"
"QLabel{\n"
"    font: 87 12pt \"Century Gothic\";\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(54, 54, 54);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    border: 0px solid #14C8DC;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: 0px;\n"
"    color: rgb(255, 255, 255);\n"
"    border-bottom: 2px solid rgb(103, 103, 103); \n"
"    font: 75 12pt \"Century Gothic\";\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    border-radius: 20px;\n"
"    background-color: rgb(103, 103, 103);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 77 13pt \"Century Gothic\";\n"
"    \n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    background-color: rgb(150, 150, 150);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    \n"
"    font: 77 13pt \"Century Gothic\";\n"
"}\n"
"\n"
"\n"
"QTableWidget{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"\n"
"    gridline-color: rgb(150, 150, 150);\n"
"\n"
"    font-size: 12pt;\n"
"\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(150, 150, 150);\n"
"\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"\n"
"    font-size: 12pt;\n"
"\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"    border: 1px solid rgb(150, 150, 150);\n"
"}")
        self.frame_paginas.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_paginas.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_paginas.setObjectName("frame_paginas")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_paginas)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_paginas)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_datos = QtWidgets.QWidget()
        self.page_datos.setObjectName("page_datos")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_datos)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(parent=self.page_datos)
        self.label.setMinimumSize(QtCore.QSize(80, 0))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.tabla_canales = QtWidgets.QTableWidget(parent=self.page_datos)
        self.tabla_canales.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.tabla_canales.setObjectName("tabla_canales")
        self.tabla_canales.setColumnCount(5)
        self.tabla_canales.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_canales.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tabla_canales.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tabla_canales.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tabla_canales.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_canales.setHorizontalHeaderItem(4, item)
        self.tabla_canales.horizontalHeader().setVisible(False)
        self.tabla_canales.horizontalHeader().setCascadingSectionResizes(False)
        self.tabla_canales.horizontalHeader().setDefaultSectionSize(180)
        self.tabla_canales.horizontalHeader().setHighlightSections(True)
        self.tabla_canales.horizontalHeader().setMinimumSectionSize(40)
        self.tabla_canales.horizontalHeader().setSortIndicatorShown(True)
        self.tabla_canales.horizontalHeader().setStretchLastSection(False)
        self.tabla_canales.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_4.addWidget(self.tabla_canales)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.bt_refrescar = QtWidgets.QPushButton(parent=self.page_datos)
        self.bt_refrescar.setMinimumSize(QtCore.QSize(120, 30))
        self.bt_refrescar.setObjectName("bt_refrescar")
        self.horizontalLayout_4.addWidget(self.bt_refrescar)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.stackedWidget.addWidget(self.page_datos)
        self.page_registrar = QtWidgets.QWidget()
        self.page_registrar.setObjectName("page_registrar")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_registrar)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(parent=self.page_registrar)
        self.label_5.setEnabled(True)
        self.label_5.setMinimumSize(QtCore.QSize(80, 0))
        self.label_5.setMaximumSize(QtCore.QSize(16777208, 60))
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(100)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(parent=self.page_registrar)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(parent=self.page_registrar)
        self.label_4.setMinimumSize(QtCore.QSize(150, 0))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(parent=self.page_registrar)
        self.label_6.setMinimumSize(QtCore.QSize(150, 0))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(100)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.page_registrar)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_5.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.page_registrar)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_5.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.page_registrar)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_5.addWidget(self.lineEdit_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(parent=self.page_registrar)
        self.label_3.setMinimumSize(QtCore.QSize(150, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        spacerItem5 = QtWidgets.QSpacerItem(368, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.bt_registrar = QtWidgets.QPushButton(parent=self.page_registrar)
        self.bt_registrar.setMinimumSize(QtCore.QSize(120, 30))
        self.bt_registrar.setObjectName("bt_registrar")
        self.horizontalLayout_6.addWidget(self.bt_registrar)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.stackedWidget.addWidget(self.page_registrar)
        self.page_borrar = QtWidgets.QWidget()
        self.page_borrar.setObjectName("page_borrar")
        self.label_17 = QtWidgets.QLabel(parent=self.page_borrar)
        self.label_17.setGeometry(QtCore.QRect(300, 30, 141, 51))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.page_borrar)
        self.label_18.setGeometry(QtCore.QRect(70, 150, 121, 71))
        self.label_18.setObjectName("label_18")
        self.lineEdit_11 = QtWidgets.QLineEdit(parent=self.page_borrar)
        self.lineEdit_11.setGeometry(QtCore.QRect(230, 170, 171, 41))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.bt_buscar_2 = QtWidgets.QPushButton(parent=self.page_borrar)
        self.bt_buscar_2.setGeometry(QtCore.QRect(510, 180, 120, 30))
        self.bt_buscar_2.setMinimumSize(QtCore.QSize(120, 30))
        self.bt_buscar_2.setObjectName("bt_buscar_2")
        self.stackedWidget.addWidget(self.page_borrar)
        self.page_actualizar = QtWidgets.QWidget()
        self.page_actualizar.setObjectName("page_actualizar")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_actualizar)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_7 = QtWidgets.QLabel(parent=self.page_actualizar)
        self.label_7.setMinimumSize(QtCore.QSize(180, 0))
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_12.addWidget(self.label_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(parent=self.page_actualizar)
        self.label_8.setMinimumSize(QtCore.QSize(300, 0))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.page_actualizar)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_9.addWidget(self.lineEdit_4)
        self.bt_buscar = QtWidgets.QPushButton(parent=self.page_actualizar)
        self.bt_buscar.setMinimumSize(QtCore.QSize(120, 30))
        self.bt_buscar.setObjectName("bt_buscar")
        self.horizontalLayout_9.addWidget(self.bt_buscar)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_12.addItem(spacerItem6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(100)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_12 = QtWidgets.QLabel(parent=self.page_actualizar)
        self.label_12.setMinimumSize(QtCore.QSize(150, 0))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_10.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(parent=self.page_actualizar)
        self.label_13.setMinimumSize(QtCore.QSize(150, 0))
        self.label_13.setObjectName("label_13")
        self.verticalLayout_10.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(parent=self.page_actualizar)
        self.label_14.setMinimumSize(QtCore.QSize(150, 0))
        self.label_14.setObjectName("label_14")
        self.verticalLayout_10.addWidget(self.label_14)
        self.horizontalLayout_8.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(100)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=self.page_actualizar)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_11.addWidget(self.lineEdit_8)
        self.lineEdit_9 = QtWidgets.QLineEdit(parent=self.page_actualizar)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_11.addWidget(self.lineEdit_9)
        self.lineEdit_10 = QtWidgets.QLineEdit(parent=self.page_actualizar)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_11.addWidget(self.lineEdit_10)
        self.horizontalLayout_8.addLayout(self.verticalLayout_11)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_12.addItem(spacerItem8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_16 = QtWidgets.QLabel(parent=self.page_actualizar)
        self.label_16.setMinimumSize(QtCore.QSize(150, 0))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_16.setText("")
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_11.addWidget(self.label_16)
        spacerItem9 = QtWidgets.QSpacerItem(368, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.bt_actualizar = QtWidgets.QPushButton(parent=self.page_actualizar)
        self.bt_actualizar.setMinimumSize(QtCore.QSize(120, 30))
        self.bt_actualizar.setObjectName("bt_actualizar")
        self.horizontalLayout_11.addWidget(self.bt_actualizar)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.stackedWidget.addWidget(self.page_actualizar)
        self.page_consultar = QtWidgets.QWidget()
        self.page_consultar.setObjectName("page_consultar")
        self.stackedWidget.addWidget(self.page_consultar)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_3.addWidget(self.frame_paginas)
        self.verticalLayout.addWidget(self.frame_contenido)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "BASE DE DATOS"))
        self.pushButton_2.setText(_translate("MainWindow", "REGISTRAR"))
        self.pushButton_3.setText(_translate("MainWindow", "BORRAR"))
        self.pushButton_4.setText(_translate("MainWindow", "ACTUALIZAR"))
        self.pushButton_5.setText(_translate("MainWindow", "CONSULTAR"))
        self.label.setText(_translate("MainWindow", "CANALES"))
        item = self.tabla_canales.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tabla_canales.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOMBRE"))
        item = self.tabla_canales.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SUSCRIPTORES"))
        item = self.tabla_canales.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "CATEGORIA"))
        item = self.tabla_canales.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ENLACE"))
        self.bt_refrescar.setText(_translate("MainWindow", "REFRESCAR"))
        self.label_5.setText(_translate("MainWindow", "REGISTRAR CANALES"))
        self.label_2.setText(_translate("MainWindow", "NOMBRE"))
        self.label_4.setText(_translate("MainWindow", "SUSCRIPTORES"))
        self.label_6.setText(_translate("MainWindow", "CATEGORÍA"))
        self.bt_registrar.setText(_translate("MainWindow", "REGISTRAR"))
        self.label_17.setText(_translate("MainWindow", "TextLabel"))
        self.label_18.setText(_translate("MainWindow", "TextLabel"))
        self.bt_buscar_2.setText(_translate("MainWindow", "REGISTRAR"))
        self.label_7.setText(_translate("MainWindow", "ACTUALIZAR CANAL"))
        self.label_8.setText(_translate("MainWindow", "NOMBRE DEL CANAL"))
        self.bt_buscar.setText(_translate("MainWindow", "BUSCAR"))
        self.label_12.setText(_translate("MainWindow", "NOMBRE"))
        self.label_13.setText(_translate("MainWindow", "SUSCRIPTORES"))
        self.label_14.setText(_translate("MainWindow", "CATEGORÍA"))
        self.bt_actualizar.setText(_translate("MainWindow", "ACTUALIZAR"))
